[versions]
agp = "8.13.2"
kotlin = "2.2.21"
googleServices = "4.4.4"
ksp = "2.2.21-2.0.4"
coreKtx = "1.17.0"
lifecycleRuntimeKtx = "2.10.0"
lifecycleViewmodelKtx = "2.10.0"
activityCompose = "1.12.1"
composeBom = "2025.12.01"
uiText = "1.10.0"

firebaseBom = "34.7.0"
materialIconsExtended = "1.7.8"
lifecycleService = "2.10.0"
uiGraphics = "1.10.0"
roomRuntime = "2.8.4"
savedstateKtx = "1.4.0"
voskAndroid = "0.3.75"
datastorePreferences = "1.2.0"
coreSplashscreen = "1.2.0"
material = "1.13.0"
ktorBom = "3.3.3"
navigationCompose = "2.9.6"
kotlinxSerializationJson = "1.9.0"
materialAdaptive = "1.2.0"
koinBom = "4.1.1"

junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-text = { group = "androidx.compose.ui", name = "ui-text", version.ref = "uiText" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-ai = { module = "com.google.firebase:firebase-ai" }

androidx-lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycleService" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "uiGraphics" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }

vosk-android = { module = "com.alphacephei:vosk-android", version.ref = "voskAndroid" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-savedstate-ktx = { module = "androidx.savedstate:savedstate-ktx", version.ref = "savedstateKtx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material-adaptive = { module = "androidx.compose.material3.adaptive:adaptive", version.ref = "materialAdaptive" }
material-adaptive-layout = { module = "androidx.compose.material3.adaptive:adaptive-layout", version.ref = "materialAdaptive" }
material-adaptive-navigation = { module = "androidx.compose.material3.adaptive:adaptive-navigation", version.ref = "materialAdaptive" }

ktor-bom = { module = "io.ktor:ktor-bom", version.ref = "ktorBom" }
ktor-client-core = { module = "io.ktor:ktor-client-core"}
ktor-client-android = { module = "io.ktor:ktor-client-android"}
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation"}
ktor-serialization-json = { module = "io.ktor:ktor-serialization-kotlinx-json"}
ktor-client-logging = { module = "io.ktor:ktor-client-logging"}

androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-ktor = { module = "io.insert-koin:koin-ktor" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[bundles]
room = [
    "androidx-room-ktx",
    "androidx-room-runtime"
]

ktor = [
    "ktor-client-core",
    "ktor-client-android",
    "ktor-client-content-negotiation",
    "ktor-serialization-json",
    "ktor-client-logging",
]

material-adaptive = [
    "material-adaptive",
    "material-adaptive-layout",
    "material-adaptive-navigation"
]

koin = [
    "koin-core",
    "koin-android",
    "koin-androidx-compose",
    "koin-compose",
    "koin-compose-viewmodel",
    "koin-ktor"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize" }